version: "3.8"
services:
  ceilingio-base-build:
    build:
      context: .
      dockerfile: Dockerfile.base
      target: build
    image: ceilingio/base:build

  ceilingio-base-runtime:
    build:
      context: .
      dockerfile: Dockerfile.base
      target: runtime
    image: ceilingio/base:runtime

  ceilingio-server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: ceilingio-server:prod
    depends_on:
      - ceilingio-base-build
      - ceilingio-base-runtime
    ports:
      - "8080:8080"
    restart: unless-stopped
