ARG BASE_BUILD_IMAGE=ceilingio/base:build

FROM ${BASE_BUILD_IMAGE} AS build

WORKDIR /src/ceilingIO
COPY . .

RUN cmake -B build -DCMAKE_BUILD_TYPE=Debug \
    -DCMAKE_PREFIX_PATH=/opt/juce-install \
    -DceilingIO_FETCH_SERVER_DEPS=ON

RUN cmake --build build --target ceilingIOServer -j"$(nproc)"

FROM ${BASE_BUILD_IMAGE} AS runtime

WORKDIR /app
COPY --from=build /src/ceilingIO/build/ceilingIOServer_artefacts/Debug/ceilingIOServer /usr/local/bin/ceilingIOServer

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/ceilingIOServer"]
CMD ["8080"]
