services:
  ceilingio-base-build:
    build:
      context: .
      dockerfile: Dockerfile.base
      target: build
    image: ceilingio/base:build

  ceilingio-base-runtime:
    build:
      context: .
      dockerfile: Dockerfile.base
      target: runtime
    image: ceilingio/base:runtime
    depends_on:
      - ceilingio-base-build

  ceilingio-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ceilingio-server:dev
    depends_on:
      - ceilingio-base-build
      - ceilingio-base-runtime
    ports:
      - "8080:8080"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    networks:
      - mastering_webapp_network

networks:
  mastering_webapp_network:
    name: mastering_webapp_network
    external: true